"""Filesystem R/W — primary interface for Obsidian vault (zero plugin dependency)."""
import datetime
import json
import logging
from pathlib import Path
from typing import Optional

logger = logging.getLogger(__name__)


class VaultError(Exception):
    """Vault operation failed."""


class Vault:
    """Direct filesystem access to Obsidian vault — works even if Obsidian is closed."""

    def __init__(self, vault_path: Path):
        self.vault_path = vault_path.resolve()
        self.daily_notes_dir = self.vault_path / "Daily Notes"
        self.memory_dir = self.vault_path / "Memory"
        self.people_dir = self.vault_path / "People"
        self.agent_dir = self.vault_path / "Agent"
        self.knowledge_dir = self.vault_path / "Knowledge"

    async def initialize(self) -> None:
        """Create vault directory structure and base files if missing."""
        dirs = [
            self.daily_notes_dir,
            self.memory_dir / "Summaries",
            self.people_dir,
            self.agent_dir,
            self.knowledge_dir,
        ]
        for d in dirs:
            d.mkdir(parents=True, exist_ok=True)
            logger.debug(f"Ensured directory: {d}")

        # Create Index.md if it doesn't exist
        index_path = self.vault_path / "Index.md"
        if not index_path.exists():
            index_path.write_text(
                """# 🗺️ BrainVault Index

Welcome to your second brain. This index auto-regenerates.

## Quick Links

- [[Memory/MEMORY]]
- [[People/USER]]
- [[Agent/IDENTITY]]
- [[Agent/SOUL]]

---
*Generated by Bridge agent*
"""
            )
            logger.info(f"Created vault index: {index_path}")

    def _ensure_extension(self, path: str) -> str:
        """Add .md extension if missing."""
        if not path.endswith(".md"):
            return f"{path}.md"
        return path

    # File read/write
    async def read_note(self, path: str) -> Optional[str]:
        """Read raw markdown of a vault note."""
        full_path = self.vault_path / self._ensure_extension(path)
        try:
            return full_path.read_text(encoding="utf-8")
        except FileNotFoundError:
            return None
        except Exception as e:
            logger.error(f"Error reading {path}: {e}")
            return None

    async def write_note(self, path: str, content: str, overwrite: bool = True) -> bool:
        """Write content to a vault note."""
        full_path = self.vault_path / self._ensure_extension(path)
        try:
            if full_path.exists() and not overwrite:
                raise VaultError(f"Note already exists: {path}")
            full_path.parent.mkdir(parents=True, exist_ok=True)
            full_path.write_text(content, encoding="utf-8")
            logger.debug(f"Wrote note: {path}")
            return True
        except Exception as e:
            logger.error(f"Error writing {path}: {e}")
            return False

    async def append_to_note(self, path: str, content: str, add_newline: bool = True) -> bool:
        """Append content to an existing note (creates if missing)."""
        full_path = self.vault_path / self._ensure_extension(path)
        try:
            full_path.parent.mkdir(parents=True, exist_ok=True)
            mode = "a"
            if add_newline and full_path.exists() and full_path.stat().st_size > 0:
                content = "\n\n" + content
            with open(full_path, mode, encoding="utf-8") as f:
                f.write(content)
            logger.debug(f"Appended to note: {path}")
            return True
        except Exception as e:
            logger.error(f"Error appending to {path}: {e}")
            return False

    async def delete_note(self, path: str) -> bool:
        """Delete a vault note."""
        full_path = self.vault_path / self._ensure_extension(path)
        try:
            if full_path.exists():
                full_path.unlink()
                logger.info(f"Deleted note: {path}")
                return True
            return False
        except Exception as e:
            logger.error(f"Error deleting {path}: {e}")
            return False

    async def note_exists(self, path: str) -> bool:
        """Check if a note exists."""
        return (self.vault_path / self._ensure_extension(path)).exists()

    # Daily Note operations
    def get_todays_note_path(self) -> str:
        """Path for today's daily note."""
        today = datetime.date.today()
        filename = f"{today.strftime('%Y-%m-%d')}.md"
        return f"Daily Note/{filename}"

    async def get_todays_note(self) -> Optional[str]:
        return await self.read_note(self.get_todays_note_path())

    async def append_to_daily(self, content: str) -> bool:
        """Append a conversation entry to today's daily note."""
        return await self.append_to_note(self.get_todays_note_path(), content)

    # Vault metadata
    async def list_notes(self, subdir: str = "") -> list[str]:
        """List all note paths relative to vault root."""
        search_dir = self.vault_path / subdir if subdir else self.vault_path
        notes = []
        for f in search_dir.rglob("*.md"):
            rel = f.relative_to(self.vault_path).as_posix()
            notes.append(rel)
        return sorted(notes)

    async def rebuild_index(self) -> bool:
        """Regenerate Index.md with wikilinks to all notes."""
        all_notes = await self.list_notes()
        lines = ["# 🗺️ BrainVault Index", "", "Auto-regenerated vault map:", ""]
        for note in all_notes:
            name = Path(note).stem
            lines.append(f"- [[{note}]]")
        content = "\n".join(lines) + "\n"
        return await self.write_note("Index.md", content, overwrite=True)
